'use client';

import { motion } from 'framer-motion';
import { BadgeCheck, CalendarDays, Github, Globe2, Linkedin, Twitter } from 'lucide-react';
import Reveal from './Reveal';

export default function Founder() {
  return <section className="px-5 py-8 sm:px-8 lg:px-12" aria-labelledby="founder-heading"><Reveal className="mx-auto max-w-[1200px]"><article className="relative overflow-hidden rounded-[27px] border border-blue-300/40 bg-[#0b1e54] px-7 py-8 text-white shadow-[0_16px_36px_rgba(19,46,122,0.32)] sm:px-9 lg:px-12 lg:py-10"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_46%_44%,rgba(55,116,255,0.5),transparent_25%),radial-gradient(circle_at_100%_8%,rgba(121,68,255,0.35),transparent_32%)]" /><div className="relative grid items-center gap-7 lg:grid-cols-[1.06fr_.78fr_1fr] lg:gap-8"><div><p className="text-[11px] font-bold tracking-[0.14em] text-blue-300">FOUNDER & DEVELOPER</p><h2 id="founder-heading" className="mt-4 max-w-[320px] text-[25px] font-bold leading-[1.35] tracking-tight">Dibuat dengan <span className="text-rose-400">♥</span> oleh satu orang yang peduli pada solusi sederhana.</h2><p className="mt-5 max-w-[330px] text-[12px] leading-6 text-blue-100/90">Oneklik.id dikembangkan dan dikelola secara independen dengan satu tujuan untuk membantu jutaan orang tampil lebih profesional di dunia digital.</p><div className="mt-6 flex gap-3"><Info icon={<CalendarDays className="h-5 w-5" />} label="Berdiri Sejak" value="2024" /><Info icon={<Globe2 className="h-5 w-5" />} label="Berbasis di" value="Indonesia" /></div></div><motion.div whileHover={{ scale: 1.025 }} className="relative mx-auto grid h-[190px] w-[190px] place-items-center rounded-full border-[5px] border-blue-200 bg-[radial-gradient(circle_at_50%_25%,#e9edf5_0%,#94a3b8_46%,#263866_100%)] shadow-[0_0_0_6px_rgba(104,139,255,0.24),0_18px_32px_rgba(0,0,0,0.35)]"><span className="text-5xl font-black tracking-[-0.12em] text-slate-900">DT</span><span className="absolute bottom-5 text-[10px] font-bold tracking-[0.22em] text-slate-700">FOUNDER</span><span className="absolute right-[-2px] top-4 grid h-9 w-9 place-items-center rounded-full bg-blue-500 text-white shadow-lg"><BadgeCheck className="h-5 w-5" /></span></motion.div><div><h3 className="text-[23px] font-bold tracking-tight">Doni Tri Nugroho</h3><p className="mt-1 text-[13px] font-semibold text-blue-400">Founder & Developer</p><p className="mt-5 max-w-[310px] text-[12px] leading-6 text-blue-100/90">Full-stack developer dan pengembang produk digital yang fokus pada solusi sederhana namun berdampak besar bagi banyak orang.</p><div className="mt-5 flex gap-3"><Social icon={<Github className="h-5 w-5" />} label="GitHub" /><Social icon={<Linkedin className="h-5 w-5" />} label="LinkedIn" /><Social icon={<Twitter className="h-5 w-5" />} label="Twitter" /></div></div></div></article></Reveal></section>;
}
function Info({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex min-w-[105px] items-center gap-2 rounded-lg border border-blue-300/30 bg-blue-500/10 px-2.5 py-2 text-blue-200"><span>{icon}</span><span><span className="block text-[8px] text-blue-200/75">{label}</span><strong className="text-[13px]">{value}</strong></span></div>; }
function Social({ icon, label }: { icon: React.ReactNode; label: string }) { return <a href="/contact" aria-label={label} className="grid h-9 w-9 place-items-center rounded-lg border border-white/20 bg-white/5 text-white transition hover:bg-white/15">{icon}</a>; }
